In [ ]:
# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board


def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player


def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

# Checks whether the player has three
# of their marks in a horizontal row


def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row


def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Board after 2 move
[[0 0 2]
 [0 0 0]
 [0 1 0]]
Board after 3 move
[[0 0 2]
 [0 0 0]
 [0 1 1]]
Board after 4 move
[[0 0 2]
 [0 0 0]
 [2 1 1]]
Board after 5 move
[[0 0 2]
 [0 1 0]
 [2 1 1]]
Board after 6 move
[[0 0 2]
 [2 1 0]
 [2 1 1]]
Board after 7 move
[[1 0 2]
 [2 1 0]
 [2 1 1]]
Winner is: 1


Certainly! Let's break down the code step by step:

1. **Importing Libraries**: The code starts by importing necessary libraries - NumPy for array manipulation, random for generating random moves, and sleep for adding delays to visualize the game.

2. **create_board()**: This function initializes the game board as a 3x3 NumPy array with all elements set to 0, indicating empty positions.

3. **possibilities(board)**: This function identifies and returns a list of all empty positions on the board.

4. **random_place(board, player)**: This function randomly selects an empty position on the board and places the mark of the current player (1 or 2) at that position. It returns the updated board.

5. **row_win(board, player)**: This function checks if the current player has three marks in a horizontal row on the board. If so, it returns True; otherwise, it returns False.

6. **col_win(board, player)**: This function checks if the current player has three marks in a vertical column on the board. If so, it returns True; otherwise, it returns False.

7. **diag_win(board, player)**: This function checks if the current player has three marks in a diagonal on the board. It checks both main diagonal and anti-diagonal. If so, it returns True; otherwise, it returns False.

8. **evaluate(board)**: This function evaluates the current state of the game. It checks for a winner by calling the row_win, col_win, and diag_win functions for both players. If any player wins, it returns the player number (1 or 2). If there is a tie, it returns -1. Otherwise, it returns 0.

9. **play_game()**: This is the main function to start the game. It initializes the board, sets the winner to 0, and starts a loop to alternate between players until there is a winner or a tie. Within each iteration, it prints the current board, waits for 2 seconds (for visualization), randomly places a mark for the current player, checks for a winner, and updates the winner variable accordingly. If there is a winner or a tie, the loop breaks, and the function returns the winner (or -1 for a tie).

10. **Driver Code**: It calls the play_game function and prints the winner of the game.

Overall, this code implements a simple text-based Tic-Tac-Toe game where players take turns making random moves until one of them wins or the game ends in a tie.

Sure, here's a shorter version of the algorithm:

1. Initialize a 3x3 game board with all positions empty.
2. Repeat until there is a winner or the board is full:

   a. Check for available positions.

   b. Randomly select a position for the current player and mark it.

   c. Check if the current player has won by having three marks in a row, column, or diagonal.

   d. If there's a winner, declare the winner and end the game.
   
   e. If the board is full and there's no winner, declare a tie.

This algorithm provides a concise overview of the key steps involved in playing a Tic-Tac-Toe game.